server.port=8090
#Datbase configuration CONNECTION
spring.datasource.url=jdbc:postgresql://localhost:5434/root
spring.datasource.username=tripagencymanagement
spring.datasource.password=root

#JPA/Hibernate autosave configuration and logging config
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

#Liquibase migration
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

#Terminal configuration
# Activar colores en la terminal
spring.output.ansi.enabled=always