# Database connection for Liquibase CLI/Maven plugin
driver=org.postgresql.Driver
url=jdbc:postgresql://localhost:5434/root
username=tripagencymanagement
password=root

# Reference (JPA entities) for diff
referenceUrl=hibernate:spring:com.tripagencymanagement.template?dialect=org.hibernate.dialect.PostgreSQLDialect
referenceDriver=liquibase.ext.hibernate.database.connection.HibernateDriver

# Changelog output
changeLogFile=src/main/resources/db/changelog/db.changelog-master.yaml
outputChangeLogFile=src/main/resources/db/changelog/changes/generated-changelog.yaml
